### ISSUE TITLE
integrate with influxdb for long term storage

### ISSUE THREAD

**Issue by m-richo** [bosh-prometheus/prometheus-boshrelease#165]
Hi,
I've been looking at using influxdb to provide long term storage.  The prometheus job already includes properties for `remote_write` and `remote_read`.  

Would you be open to a PR that would include the following.
1. operator file to deploy an influxdb instance
2. update `prometheus.yml` template from prometheus job to optionally set `remote_write` and `remote_read` based on BOSH link data from the influxdb instance.

NOTE: i did spend time looking at building a BOSH job for `remote_storage_adapter` based on https://github.com/prometheus/prometheus/tree/release-2.1/documentation/examples/remote_storage/remote_storage_adapter but it now appears that influxdb 1.4.x supports the prometheus read/write natively.

Cheers,
Michael

**Comment by frodenas** [comment]
@m-richo What `influxdb` bosh release do you plan to add at the op-file?

**Comment by m-richo** [comment]
i had a look around and thought the following from the concourse folk was most active
https://github.com/concourse/influxdb-boshrelease

it's a fork, but they don't appear to be upstreaming.

I've raised a PR to them to add BOSH links and intended to raise another to upgrade influxdb from 1.3 to 1.4.3 (current) which supports prometheus remote storage natively.

**Comment by frodenas** [comment]
@Alexvianet I have never tried it, maybe @m-richo has updates?

**Comment by Alexvianet** [comment]
works well with https://github.com/cloudfoundry-community/influxdb-boshrelease
```
properties:
   prometheus:
      remote_write:
        - url: http://influxdb:8086/api/v1/prom/write?u=user&p=pass&db=yourdb
      remote_read:
        - url: http://influxdb:8086/api/v1/prom/read?u=user&p=pass&db=yourdb
```
