### ISSUE TITLE
Unable to read from firehose_exporter and cf_exporter using nats properties

### ISSUE THREAD

**Issue by makknife** [bosh-prometheus/prometheus-boshrelease#174]
My prometheus-boshrelease was working great when I deployed it on the same BOSH as PCF, but now I'm having issues when prometheus is on a separate BOSH.

I'm able to view PCF BOSH data in grafana, but not CF data.
The only change I made was removing `cloud_controller` and introducing `nats` properties.
This is in the operator file below.

[disable-cloud-controller-links.yml]
```
# route_registrar
- type: remove
  path: /instance_groups/name=nginx/jobs/name=route_registrar/consumes/nats
- type: replace
  path: /instance_groups/name=nginx/jobs/name=route_registrar/properties/nats?/port?
  value: 4222
- type: replace
  path: /instance_groups/name=nginx/jobs/name=route_registrar/properties/nats?/user?
  value: nats
- type: replace
  path: /instance_groups/name=nginx/jobs/name=route_registrar/properties/nats?/password?
  value: ((nats_password))
- type: replace
  path: /instance_groups/name=nginx/jobs/name=route_registrar/properties/nats?/machines?
  value:
  - ((nats_ip1))
  - ((nats_ip2))
```

All the other operators have only been slightly modified for custom persistent disk types, azs, etc.

```
yes | bosh2 -e ops-bosh \
      -d prometheus \
      deploy prometheus-boshrelease/manifests/prometheus.yml \
        --vars-store ${home}/${output_dir}/credentials.yml \
        -v bosh_url=$PCF_BOSH_URL \
        -v uaa_bosh_exporter_client_secret=$UAA_BOSH_EXPORTER_CLIENT_SECRET \
        -v metrics_environment=$METRICS_ENVIRONMENT \
        -v metron_deployment_name=cf \
        -v system_domain=$SYSTEM_DOMAIN \
        -v nats_password="$NATS_PASSWORD" \
        -v nats_ip1="$NATS_IP1" \
        -v nats_ip2="$NATS_IP2" \
        -v aws_region=$AWS_REGION \
        -v aws_az=$AWS_AZ \
        -v vm_type_med=$VM_TYPE_MED \
        -v network_name=$NETWORK_NAME \
        -v disk_type_sm=$DISK_TYPE_SM \
        -v disk_type_lg=$DISK_TYPE_LG \
        -v uaa_clients_cf_exporter_secret=$UAA_CLIENTS_CF_EXPORTER_SECRET \
        -v uaa_clients_firehose_exporter_secret=$UAA_CLIENTS_FIREHOSE_EXPORTER_SECRET \
        -v traffic_controller_external_port=4443 \
        -v skip_ssl_verify=false \
        --var-file bosh_ca_cert=$PCF_BOSH_CERT_PATH \
        -o prometheus-boshrelease/manifests/operators/monitor-bosh.yml \
        -o prometheus-boshrelease/manifests/operators/enable-bosh-uaa.yml \
        -v slack_webhook=$SLACK_WEBHOOK \
        -o manifests/operators/alertmanager-email-receiver.yml \
        -o manifests/operators/alertmanager-slack-receiver.yml \
        -o manifests/operators/monitor-cf.yml \
        -o manifests/operators/set-azs.yml \
        -o manifests/operators/enable-cf-route-registrar.yml \
        -o manifests/operators/disable-cloud-controller-links.yml
```

The uaa clients are made using the uaac binary and not with the provided operators  (using uaa.yml, add-bosh-exporter-uaa-clients.yml, etc.).
We do not have the ability to make updates to the BOSH where PCF lives.

So we are doing it like this

```
uaac target ${PCF_UAA_URL} --skip-ssl-validation

uaac token client get admin -s ${UAA_ADMIN_CLIENT_PASSWORD}

# Firehose Exporter
args="
      --name firehose_exporter \
  	  --authorized_grant_types client_credentials,refresh_token \
  	  --authorities doppler.firehose \
      --scope openid,doppler.firehose
  	 "
uaac client add firehose_exporter $args \
	--secret ${UAA_CLIENTS_FIREHOSE_EXPORTER_SECRET}

# CF Exporter
args="
      --name cf_exporter \
      --authorized_grant_types client_credentials,refresh_token \
      --authorities cloud_controller.admin \
      --scope openid,cloud_controller.admin
  	 "

uaac client add cf_exporter $args \
	--secret ${UAA_CLIENTS_CF_EXPORTER_SECRET}

uaac target ${PCF_BOSH_UAA_URL} --skip-ssl-validation

printf '%s\n' admin ${UAA_ADMIN_USER_CREDENTIALS} > ./creds
uaac token owner get login -s ${UAA_LOGIN_CLIENT_CREDENTIALS} < ./creds

# Bosh Exporter
args="
      --name bosh_exporter \
      --authorized_grant_types client_credentials,refresh_token \
      --authorities bosh.read \
      --scope bosh.read
     "

uaac client add bosh_exporter $args \
	--secret ${UAA_BOSH_EXPORTER_CLIENT_SECRET}
```

Here is some of my log output

[prometheus.stderr.log]
```
time="2018-03-14T14:20:26Z" level=error msg="Error adding file watch for "/var/vcap/store/bosh_exporter": no such file or directory" source="file.go:106"
```

[cf_exporter.stderr.log]
```
time="2018-03-14T14:20:28Z" level=info msg="Listening on :9193" source="cf_exporter.go:283"
```

[firehose_exporter.stderr.log]
```
time="2018-03-14T14:19:45Z" level=info msg="Listening on :9186" source="firehose_exporter.go:328"
time="2018-03-14T14:19:45Z" level=info msg="Starting Firehose Nozzle..." source="firehose_nozzle.go:58"
```
Do anyone know what might be causing this issue?

Thanks!
