### ISSUE TITLE
Question how to map dynamic ip in to manifest of neighbor job

### ISSUE THREAD

**Issue by Alexvianet** [bosh-prometheus/prometheus-boshrelease#189]
HI sorry for disturb, can someone help how to map(link) dynamic ip of  neighbor job in to manifest.
I have fond hot to map static_ips: "(( jobs.postgres.networks.default.static_ips.[0] ))" but can't get how to map dynamic =(
Help please

**Comment by Alexvianet** [comment]
also, a know how to map dynamic IP in templates but I need to do such in the manifest like:
```
    properties:
      alertmanager:
        receivers:
          - name: slack-receiver
            webhook_configs:
              - url: (( concat "http://" jobs.prom2teams.networks.dynamic.[0] ":8089/v2/Connector" ))
                send_resolved: true
```
