### ISSUE TITLE
firehose_exporter and cf_exporter not collecting data..

### ISSUE THREAD

**Issue by fgraichen** [bosh-prometheus/prometheus-boshrelease#190]
Boths show as started in the logs but I am not seeing any data flow through to Grafana.  

The stdout logs remain at zero length and I am seeing no errors in the other logs..just the start messages and the "listening" message on the firehose.

To be honest I am not clear what grafana dashboards are fed via the firehose versus cf_exporter.  

Thanks in advance

**Comment by benjaminguttmann-avtq** [comment]
Hi @fgraichen , the default log level is not that helpful. To see more details you have to increase the log level to debug. More or less all dashboards not starting with `Bosh` but with `CF` and `Apps` are fed via the firehose and cf_exporter. Am I right in the assumption that your bosh exporter is working as expected? Did you use the provided ops files of the prometheus repository to set up prometheus or are you using some own manifest? You can try to curl the metrics endpoint of the exporters and see if you receive some error on that. You can find the targets in the Prometheus UI > Status > Targets.

**Comment by fgraichen** [comment]
You are correct.  BOSH is working fine.   How do I increase the log levels ?    If I understand correctly the cf exporter is hitting the standard cf apis to get information.   What causes that to “fire”??   I guess same question for the firehose.    When I look at the monitor_cf yml it has an entry for metron deployment but I don’t see a metron vm running except on an older cf deployment running pcf metrics. Is this the metron that comes with pcf metrics?   Is this the same for 2.1 instances of pcf ?   Do I neeed to be running pcf metrics?

**Comment by fgraichen** [comment]
I am not seeing the firehose nor the cf_exporters defined as targets when I log into the promethues console.  I just see the node and the bosh exporters..  Is it possible that since these were originally configured incorrectly that that prvented them from being set in prometheus?

**Comment by fgraichen** [comment]
I hit the cf_exporter running instance on the prometheus VM with /metrics and it returned metric data so it just seems for some reason the prometheus targets are not set

**Comment by benjaminguttmann-avtq** [comment]
@fgraichen : Okay. Let me answer your questions 1 by 1. 

1) Increasing the log level can be done via properties in the manifest. You can find the properties to do so https://github.com/bosh-prometheus/prometheus-boshrelease/blob/8fb0807693a7101c42285fc7e83bac8f8a48b862/jobs/cf_exporter/spec#L29-L30 and https://github.com/bosh-prometheus/prometheus-boshrelease/blob/8fb0807693a7101c42285fc7e83bac8f8a48b862/jobs/firehose_exporter/spec#L39-L40
2) There should be one metron agent on nearly every VM itself. No additional metron VMs. Please make sure to configure the same metron_name in Prometheus as configured in your environment ( for PCF it is hardcoded to CF) 
3) The exporters are caused to 'fire' if something tries to 'GET' the /metrics endoint. That is configured via the scrape configuration of the Prometheus. There is also the scrape interval/timeout configured.
4) It sounds like the CF Exporter is not on the same VM as the Prometheus. Is that right? Per default Prometheus uses service discovery to find the different exporters but this only works for exporters placed on the Prometheus VM. If this is not the case for you you have to configure the scraping in your Prometheus by yourself. This can be done here: https://github.com/bosh-prometheus/prometheus-boshrelease/blob/a686e5c30f284fafe3eed17a2975cd6fcb4d5ba1/jobs/prometheus/spec#L41-L42
The configuration should look something like that: 
```
        scrape_configs:
          scrape_interval: 5m
          scrape_timeout: 4m
        - job_name: prometheus
          static_configs:
          - targets:
            - localhost:9090
        - job_name: firehose_exporter
          static_configs:
          - targets:
            - <replace_with_firehose_exporter_vm_ip>:9186
        - job_name: cf_exporter
          static_configs:
          - targets:
            - <replace_with_exporter_exporter_vm_ip>:9193
```

I hope this will help you.
