### ISSUE TITLE
alertmanager How can configure alert message send  to mail 

### ISSUE THREAD

**Issue by leolzbing521** [bosh-prometheus/prometheus-boshrelease#208]
alertmanager How can configure alert message send  to mail

**Comment by frodenas** [comment]
You need to create an op-file to add the [alertmanager email configuration](https://prometheus.io/docs/alerting/configuration/#%3Cemail_config%3E), and apply it to your deployment. 

An example may be:

```
- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/receivers/name=default/email_configs?/-
  value:
    to: # The email address to send notifications to
    from: # The sender address.
    smarthost: # The SMTP host through which emails are sent.
```
