### ISSUE TITLE
Custom Rules in prometheus

### ISSUE THREAD

**Issue by manaspatkar21** [bosh-prometheus/prometheus-boshrelease#211]
How to add custom rules in prometheus

Here is what I have in custom-rules.yml file

---
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value: |-
    groups:
     - name: pmysqlrule
       rules:
       - alert: PMysqlServerAvailability
          expr: avg(firehose_value_metric_p_mysql_p_mysql_available) by(enveronment, bosh_deployment, bosh_job_name, bosh_job_ip) < 1
          for: 5m
          labels:
            service: p-mysql
            severity: warning
          annotations:
                  summary: "MySQL v1 for PCF instance `{{$labels.environment}}/{{$labels.bosh_deployment}}/{{$labels.bosh_job_name}}/{{$labels.bosh_job_ip}}` server not availble"
                  description: "MySQL v1 instance at `{{$labels.environment}}/{{$labels.bosh_deployment}}/{{$labels.bosh_job_name}}/{{$labels.bosh_job_ip}}` server not available during the last 5m"
$

Please help
I receive a YAML Unmarshal error in prometheus error logs

**Comment by benjaminguttmann-avtq** [comment]
hmm..

for me it looks like this:

```
  - name: alertGroupName
    rules:
      - alert: alertName1
        expr: metric > 5
        labels:
          severity: critical
          environment: "{{$labels.environment}}"
        annotations:
          summary: "Message (currently: {{$value}})"
  - name: alertGroupName2
    rules:
      - alert: alertNameA
        expr: metric{az="z1"} < 1
        for: 5m
        labels:
          severity: critical
          environment: dev
        annotations:
          summary: "Summary message"
      - alert: alertNameB
        expr: changes(metric[24h]) < 1
        for: 1h
        labels:
          severity: critical
          environment: dev
        annotations:
          summary: "Summary message"

```

I think you should have a look at your indention, at least for `severity`,`service`, and `summary` it looks not right.
