### ISSUE TITLE
Configuration of credhub_exporter not working

### ISSUE THREAD

**Issue by amuessig** [bosh-prometheus/prometheus-boshrelease#248]
Hi all,

I want to use `credhub_exporter` for monitoring the expiration dates of the bosh certificates.
However, I cannot find any metrics for this use case in prometheus. I also enabled `credhub_alerts` and modified the properties but I did not receive any alerts.
 
I applied the following ops-file:
```
- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: credhub_exporter
    release: prometheus
    properties:
      credhub_exporter:
        credhub:
          api_url: https://((master_director_ip)):8844
          client_id: credhub_exporter
          client_secret: ((/director/uaa/clients/credhub_exporter))
          ca_certs: ((/director/credhub/credhub_ca/ca))
        metrics:
          deployment: bosh-credhub
          environment: ((environment_name))
        skip_ssl_verify: ((skip_ssl_verify))

- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: credhub_alerts
    release: prometheus
    properties:
      credhub_alerts:
        certificate_expire:
          threshold: 60
          evaluation_time: 1h
        scrape_too_old:
          evaluation_time: 1m

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: credhub
    scrape_interval: 30m
    scrape_timeout: 4m
    static_configs:
    - targets:
      - localhost:9358

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/credhub_alerts/*.alerts.yml
```

Any idea why it is not working or did I check the wrong metrics? I was looking for metrics listed under: https://github.com/orange-cloudfoundry/credhub_exporter
