### ISSUE TITLE
Http_config for alertmanager not working as expected

### ISSUE THREAD

**Issue by bonzofenix** [bosh-prometheus/prometheus-boshrelease#260]
When setting multi level properties for alertmanager's http_config, job does not start property. 

Operation example file:

```
- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties?/alertmanager/http_config
  value:
    tls_config:
      insecure_skip_verify: ((alertmanager_insecure_skip_verify))
```

Alertmanager compiled template:
```
global:
...

  http_config: {"tls_config"=>{"insecure_skip_verify"=>true}
...
```

Error:
```
level=error ts=2018-11-12T15:38:25.182953709Z caller=main.go:325 msg="Loading configuration file failed" file=/var/vcap/jobs/alertmanager/config/alertmanager.yml err="yaml: line
34: did not find expected ',' or '}'"
**
```
It looks like https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/alertmanager/templates/config/alertmanager.yml#L67 might need to be html_config.to_yaml ?
