### ISSUE TITLE
Some metrics not displayed in Grafana's "Apps: System" dashboard

### ISSUE THREAD

**Issue by mnk628** [bosh-prometheus/prometheus-boshrelease#318]
Hi, 

Here's how the metrics disappear in Grafana:

1. I upgraded PAS from v2.3.8 to v2.4.7.
2. The release notes of PAS stated that the cf value in metrics were changed to cf-GUID, so I changed the value of metron_deployment_name of Prometheus and redeployed Prometheus.
3. Some metrics were no longer displayed in Grafana's Apps: System dashboard. Specifically, columns other than Instances ("CPU Usage by Application Instance"," Memory Usage by Application Instance" and "Allocated Disk Space by Application Instance" etc.) could not be seen.
4. After reviewing the PAS settings and unchecking "Use “cf” as deployment name in emitted metrics instead of unique name" in order not to use cf, the missing metrics were displayed like before upgrating PAS.
5. However, after upgrading Prometheus (from v23.4.0 to v25.0.0), the metrics no longer are displayed in the Grafana Apps: System dashboard again. As I experienced at the phase 3, no fields other than Instances ("CPU Usage by Application Instance"," Memory Usage by Application Instance" and "Allocated Disk Space by Application Instance" etc.) can be seen.
6. To try to solve the problem, I changed the value of "use_legacy_firehose" of prometheus from false to true and redeployed, but in addition to Apps: System, "BOSH: Jobs" dashboard is also displayed as "Unable to load datasource meta data" and no metrics are displayed. So I restored the settings of "use_legacy_firehose".

Could you tell me the cause and how to resolve this issue?

Thanks.

**Comment by benjaminguttmann-avtq** [comment]
Hi @mnk628 ,

but the dropdown does show some values? Or isn't any value in there?

**Comment by mnk628** [comment]
Hi @benjaminguttmann-avtq ,
Thank you for your reply.

Unfortunately, metrics and the dropdown are only visible in Instances, and there are no value and dropdowns in other metrics. Here is the screen shot.
<img width="960" alt="20190703_grafana_apps_system" src="https://user-images.githubusercontent.com/52313616/60579087-5d3a6a80-9dbd-11e9-847c-288ea5a3e990.png">

**Comment by benjaminguttmann-avtq** [comment]
Hi @mnk628 ,

okay. Just to mention it here because the screenshot is not the best example for the fact that there are not data points available. If the app is currently stopped ( and was in that state for the last hour) than actually there was no data available and the dashboard shows no data points available, please make sure to test against an app that is actually is running state

**Comment by mnk628** [comment]
Sorry, I didn't consider about status of the app.

This is Grafana screenshot of the running app "sampleapp". 
Grafana should display some values if the app is running, but it doesn't show any metrics other than Instances.
<img width="960" alt="20190704_grafana_apps_system" src="https://user-images.githubusercontent.com/52313616/60639637-6f201a00-9e5e-11e9-80dc-aea448ac80ca.png">
And here is Apps Manager screenshot that shows the status of "sampleapp".
You can see that sampleapp is really running.
<img width="960" alt="20190704_app_list" src="https://user-images.githubusercontent.com/52313616/60639643-7515fb00-9e5e-11e9-839e-0b5215cc7d8e.png">

In addition, I will inform you that there are other 2 issues after the upgrade of prometheus from v23.4.0 to v25.0.0.
Are these related to the problem of Grafana's Apps: System?

1. Since the upgrading, prometheus has been triggered  some alerts, "FirehoseExporterLastMetricReceivedTooOld" and "FirehoseExporterLastEnvelopeReceivedTooOld".
2. Grafana shows the prometheus2 VM has high CPU usage since the upgrading. I accessed the prometheus2 VM and execute top command. As a result, I found that the CPU usage of "firehose_export" was abnormally high.
```
top - 02:09:34 up 9 days, 10:20,  1 user,  load average: 1.73, 1.67, 1.64
Tasks: 103 total,   1 running,  63 sleeping,   0 stopped,   0 zombie
%Cpu(s): 62.8 us, 10.3 sy,  0.0 ni, 27.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  4040052 total,  1003788 free,  1168532 used,  1867732 buff/cache
KiB Swap:  4039676 total,  4037508 free,     2168 used.  2612716 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 1004 root      10 -10  255884 155840  11584 S 145.0  3.9  11304:22 firehose_export
    7 root      20   0       0      0      0 S   0.3  0.0  20:30.85 ksoftirqd/0
    1 root      20   0   37692   5960   4188 S   0.0  0.1   0:03.81 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.06 kthreadd
    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/0:0H
    6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_wq
    8 root      20   0       0      0      0 I   0.0  0.0  10:13.61 rcu_sched
    9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 rcu_bh
   10 root      rt   0       0      0      0 S   0.0  0.0   0:00.04 migration/0
   11 root      rt   0       0      0      0 S   0.0  0.0   0:01.15 watchdog/0
   12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0
   13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1
   14 root      rt   0       0      0      0 S   0.0  0.0   0:01.12 watchdog/1
   15 root      rt   0       0      0      0 S   0.0  0.0   0:00.03 migration/1
   16 root      20   0       0      0      0 S   0.0  0.0  20:52.83 ksoftirqd/1
   18 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/1:0H
   19 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kdevtmpfs
   20 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 netns
   21 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_tasks_kthre
   22 root      20   0       0      0      0 S   0.0  0.0   0:00.47 kauditd
   24 root      20   0       0      0      0 S   0.0  0.0   0:00.20 khungtaskd
   25 root      20   0       0      0      0 S   0.0  0.0   0:00.00 oom_reaper
   26 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 writeback
```

**Comment by benjaminguttmann-avtq** [comment]
@mnk628 : Thanks for the additional information, that might gave the right hint. As we can see [here](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/76476e9ecf920094ef52e4fab7cf9a89c8d95236/jobs/cloudfoundry_dashboards/templates/cf_apps_system.json#L831), for example, the metrics you expect to see in the Grafana Dashboard are gathered from the firehose exporter, which seems to have some trouble. 

Two things are interesting here:

1. Can you please check the logs of the firehose exporter for some error logs? (/var/vcap/sys/log/firehose_exporter/*)
2. Does a `monit restart firehose_exporter` resolve the situation or is the CPU usage increasing again that much? 

I think there was a switch in the firehose exporter to use a different API to gather logs, maybe this is related to this.

**Comment by mnk628** [comment]
Hi @benjaminguttmann-avtq ,

1. Checking the log "firehose_exporter.stderr.log" which seems to be valid, I found that firehose_exporter frequently had retried with "too many open files" error.
```
prometheus2/3a59a2bd-75ff-48b4-8421-2ea715b1b4f9:/var/vcap/sys/log/firehose_exporter# ls -ltr
total 13344
-rw-r--r-- 1 root root        0 Jun 25 07:26 firehose_exporter.stdout.log
-rw-r--r-- 1 root root      437 Jun 27 08:55 firehose_exporter_ctl.stdout.log
-rw-r--r-- 1 root root       91 Jun 27 08:55 firehose_exporter_ctl.stderr.log
-rw-r--r-- 1 root root 13651950 Jun 28 20:10 firehose_exporter.stderr.log
prometheus2/3a59a2bd-75ff-48b4-8421-2ea715b1b4f9:/var/vcap/sys/log/firehose_exporter#
prometheus2/3a59a2bd-75ff-48b4-8421-2ea715b1b4f9:/var/vcap/sys/log/firehose_exporter#
prometheus2/3a59a2bd-75ff-48b4-8421-2ea715b1b4f9:/var/vcap/sys/log/firehose_exporter#
prometheus2/3a59a2bd-75ff-48b4-8421-2ea715b1b4f9:/var/vcap/sys/log/firehose_exporter# tail -20 firehose_exporter.stderr.log
2019/06/28 20:10:20 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 1s
2019/06/28 20:10:21 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 1s
2019/06/28 20:10:22 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 1s
2019/06/28 20:10:23 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 1s
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 5ms
2019/06/28 20:10:24 http: Accept error: accept tcp 0.0.0.0:9186: accept4: too many open files; retrying in 10ms
prometheus2/3a59a2bd-75ff-48b4-8421-2ea715b1b4f9:/var/vcap/sys/log/firehose_exporter#
```

2. After executing "monit restart firehose_exporter", I executed "top" command. But CPU usage of firehose_export still be high.
```
top - 01:27:46 up 11 days,  9:38,  1 user,  load average: 1.58, 1.53, 1.55
Tasks: 105 total,   2 running,  65 sleeping,   0 stopped,   0 zombie
%Cpu(s): 61.2 us, 11.3 sy,  0.0 ni, 27.4 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem :  4040052 total,  1116072 free,  1153904 used,  1770076 buff/cache
KiB Swap:  4039676 total,  4037212 free,     2464 used.  2534212 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
19396 root      10 -10  187720 138044  11648 R 142.5  3.4   3:41.62 firehose_export
    7 root      20   0       0      0      0 S   0.3  0.0  26:27.52 ksoftirqd/0
   16 root      20   0       0      0      0 S   0.3  0.0  26:55.26 ksoftirqd/1
29737 vcap       5 -15  540152  17672  11976 S   0.3  0.4  15:50.63 bosh-dns
    1 root      20   0   37692   5960   4188 S   0.0  0.1   0:04.18 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.08 kthreadd
    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/0:0H
    6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_wq
    8 root      20   0       0      0      0 I   0.0  0.0  12:46.92 rcu_sched
    9 root      20   0       0      0      0 I   0.0  0.0   0:00.00 rcu_bh
   10 root      rt   0       0      0      0 S   0.0  0.0   0:00.05 migration/0
   11 root      rt   0       0      0      0 S   0.0  0.0   0:01.38 watchdog/0
   12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0
   13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1
   14 root      rt   0       0      0      0 S   0.0  0.0   0:01.35 watchdog/1
   15 root      rt   0       0      0      0 S   0.0  0.0   0:00.04 migration/1
   18 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/1:0H
   19 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kdevtmpfs
   20 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 netns
   21 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_tasks_kthre
   22 root      20   0       0      0      0 S   0.0  0.0   0:00.57 kauditd
   24 root      20   0       0      0      0 S   0.0  0.0   0:00.24 khungtaskd
   25 root      20   0       0      0      0 S   0.0  0.0   0:00.00 oom_reaper
```

**Comment by benjaminguttmann-avtq** [comment]
@mnk628 : The too many open files could be the issue here, as temporary fix you could do the following, open the file 

`/var/vcap/jobs/firehose_exporter/bin/firehose_exporter_ctl` and add the following to [this](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/76476e9ecf920094ef52e4fab7cf9a89c8d95236/jobs/firehose_exporter/templates/bin/firehose_exporter_ctl#L23) line: 

`ulimit -n 64000`

Afterwards you need to monit restart the firehose_exporter. 

This should at least temporary resolve the too many open files. Maybe with that modification the firehose exporter is able to get into a normal state, if not you might need to scale the VM to get more CPU.

**Comment by mnk628** [comment]
Hi @benjaminguttmann-avtq ,
Sorry for late reply.

Thank you for your advice.
I set the higher value of files that can be accessed and executed monit restart firehose_exporter.
As a result, the CPU usage for firehose has dropped significantly. Thank you.
<img width="960" alt="20190708_grafana_prometheus" src="https://user-images.githubusercontent.com/52313616/60784630-93dffe80-a18a-11e9-81d0-c02f5ee0520e.png">

However, Grafana's Apps: System still doesn't display metrics correctly. Moreover, the metrics for Instances are broken in places.
<img width="960" alt="20190708_grafana_apps_system" src="https://user-images.githubusercontent.com/52313616/60784536-44013780-a18a-11e9-879a-6cafa5f62178.png">

In addition, Prometheus has continued firing "FirehoseExporterLastMetricReceivedTooOld" alert and "FirehoseExporterLastEnvelopeReceivedTooOld" alert. Could you tell me how to resolve the issues?

**Comment by mnk628** [comment]
I'll tell you additional information.
After monit restart, Prometheus has fired new alert "CFExporterApplicationsScrapeError"  every 10 minutes.
Is this related to the problem of Grafana's Apps: System?

**Comment by benjaminguttmann-avtq** [comment]
Hm.. when switching to the newest version of Prometheus, the firehose exporter defaults to use the trafficcontroller v2 api. Therefore you need to either provide a valid `log-stream-url` or tell the firehose_exporter to use the [legacy_version ](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/76476e9ecf920094ef52e4fab7cf9a89c8d95236/jobs/firehose_exporter/spec#L45).

**Comment by mnk628** [comment]
Could you check if "logging url" and "use legacy firehose" are set correctly for "prometheus-local-firehose-cf-exporter.yml" in my own ops file? Although I added the setting to this ops file by the version upgrade of Prometheus this time, it may be wrong.

The process to configure this ops file is below:

1. Before the upgrade of Prometheus, the contents of "prometheus-local-firehose-cf-exporter.yml" were as follows. (Actually it worked normally with that setting.)
```
# delete firehose instance_group
- type: remove
  path: /instance_groups/name=firehose

# run firehose_exporter job on the prometheus instance_group
- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: firehose_exporter
    release: prometheus
    properties:
      firehose_exporter:
        doppler:
          url: wss://doppler.((system_domain)):((traffic_controller_external_port))
          subscription_id: "((metrics_environment))"
          max_retry_count: 300
        uaa:
          url: https://uaa.((system_domain))
          client_id: firehose_exporter
          client_secret: "((uaa_clients_firehose_exporter_secret))"
        metrics:
          environment: "((metrics_environment))"
        skip_ssl_verify: ((skip_ssl_verify))

# add local firehose_exporter as a target
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: firehose_exporter
    static_configs:
    - targets:
      - localhost:9186


- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
      job_name: cf_exporter
      static_configs:
      - targets:
        - localhost:9193

- type: remove
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/job_name=cf

- type: remove
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/job_name=firehose
```

2. When I tried to upgrade Prometheus, the upgrade was interrupted with the following error.
```
Task 2049669 | 01:25:24 | Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'prometheus2'. Errors are:
    - Unable to render templates for job 'firehose_exporter'. Errors are:
      - Error filling in template 'firehose_exporter_ctl' (line 67: Can't find property '["firehose_exporter.logging.url"]')
```

3. Therefore, I added "logging url" and "use legacy firehose" to line 24 in "prometheus-local-firehose-cf-exporter.yml" . (This is the current setting.)
```
# delete firehose instance_group
- type: remove
  path: /instance_groups/name=firehose

# run firehose_exporter job on the prometheus instance_group
- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: firehose_exporter
    release: prometheus
    properties:
      firehose_exporter:
        doppler:
          url: wss://doppler.((system_domain)):((traffic_controller_external_port))
          subscription_id: "((metrics_environment))"
          max_retry_count: 300
        uaa:
          url: https://uaa.((system_domain))
          client_id: firehose_exporter
          client_secret: "((uaa_clients_firehose_exporter_secret))"
        metrics:
          environment: "((metrics_environment))"
        skip_ssl_verify: ((skip_ssl_verify))
        logging:
          url: wss://doppler.((system_domain)):((traffic_controller_external_port))
          use_legacy_firehose: false

# add local firehose_exporter as a target
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: firehose_exporter
    static_configs:
    - targets:
      - localhost:9186


- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
      job_name: cf_exporter
      static_configs:
      - targets:
        - localhost:9193

- type: remove
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/job_name=cf

- type: remove
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/job_name=firehose
```

4. Later, when Prometheus was deployed again, the upgrade was completed without the above error.
However, because the metrics display in Grafana is lacking, it seems that the settings are not working properly.


5. When "use legacy firehose" was set to true in "prometheus-local-firehose-cf-exporter.yml", in addition to the Apps: System, BOSH: Jobs didn't display all metrics in Grafana, so I changed back the setting to false.
