### ISSUE TITLE
supporting external database (RDS) as grafana database

### ISSUE THREAD

**Issue by addisflava** [bosh-prometheus/prometheus-boshrelease#338]
currently the deployment use internal database and i get an error when i try to specify  the rds address as a host in the manifest . I  see in the grafana.ini  that in many places its using the first instance address

"addr=#{link('database').instances.first.address}:#{p('

**Comment by frodenas** [comment]
You need to use [bosh manual links](https://bosh.io/docs/links-manual/) to override the internal link, something like this:

```
instance_groups:
- name: grafana
  jobs:
  - name: grafana
    release: prometheus
    consumes:
      database:
        instances:
        - address: <rds ip address>
   properties:
     ...
```
