### ISSUE TITLE
Set Alertmanager Proxy not working 

### ISSUE THREAD

**Issue by giva01121** [bosh-prometheus/prometheus-boshrelease#379]
Hello, I've tried multiple scenarios to setup http_proxy via ops file, but it's not working. I'm testing it with a curl request to https://api.opsgenie.com, but it's failing. If I set manually `export http_proxy=http://blabla.bla:8080` the opsgenie address is resolved successfully.
There's no error in the alertmanager vm's logs, also I've searched in the whole environment itself for the proxy, but there's nothing appearing. I'm using the latest release from master branch.

Here I will list the ops I've tried:
#1
```
- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties?/env/http_proxy
    value: http://blabla.bla:8080
```
#2

```
- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties?/http_config/proxy_url
  value: http-proxy.schwarz:8080
```
#3
```

**Comment by gcordierOrange** [comment]
Hello,

You can use this configuration :
```
- type: replace
  path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/http_config?
  value:
    proxy_url: http://proxy_host:proxy_ip
```
It work for us.
