### ISSUE TITLE
Configuring prometheus to use a different alertmanager

### ISSUE THREAD

**Issue by pcfadminx** [bosh-prometheus/prometheus-boshrelease#433]
I have an existing alertmanager instance that I want prometheus to use.   But, I am not sure how to properly make an ops file to change this in the deployment manifest.

I have gotten this concept to work manually by modifying prometheus.yml in /var/vcap/jobs/prometheus2/config inside the running prometheus instance.  Specifically this part: 

```
alerting:
  alert_relabel_configs: []
  alertmanagers:
    - static_configs:
        - targets:
            - 10.10.10.10:9093
```

It works if I change it to this, for example:

```
alerting:
  alert_relabel_configs: []
  alertmanagers:
    - static_configs:
        - targets:
            - http://my_standalone_alertmanager:9093
```

So for a solution.  I was thinking, something like this (below) would work.  Am I on the right track?

```
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus2/alerting/name=default/alerting/-
  value:
    alertmanagers:
      - static_configs:
          - targets:
              - http://my_standalone_alertmanager:9093
```

Any help is appreciated.  Thank you.

**Comment by benjaminguttmann-avtq** [comment]
Hi @pcfadminx 

I think the you want to use the following spec:

https://github.com/bosh-prometheus/prometheus-boshrelease/blob/66868a788deb46f6ebe7cbe9482c55a09e120980/jobs/prometheus2/spec#L55

to define your alertmanager config. 
Let me suggest you an adjusted version of your ips file.

```
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/alertmanagers/-
  value:
    static_configs:
    - targets:
      - https://my_standalone_alertmanager:9093
```

**Comment by pcfadminx** [comment]
@benjaminguttmann-avtq

Thank you for your advice, I will try it out.

**Comment by pcfadminx** [comment]
Hello,

Using that that ops file, I can see the change went through when I fetch the prometheus manifest for bosh.

In the manifest it appears like this:
```
  jobs:
  - name: prometheus2
    properties:
      prometheus:
        alertmanagers:
        - static_configs:
          - targets:
            - https://my_standalone_alertmanager:9093
```

However, I can see that prometheus is still sending alerts to the default alertmanager included with the deployment instead of the "https://my_standalone_alertmanager:9093"

**Comment by pcfadminx** [comment]
@benjaminguttmann-avtq 

I made a deployment using that ops file.  I can see the change went through when I fetch the prometheus manifest for bosh.  But, alerts are still going to the default alertmanager included in bosh-prometheus.

The relevant manifest section of it appears like this:
```
  jobs:
  - name: prometheus2
    properties:
      prometheus:
        alertmanagers:
        - static_configs:
          - targets:
            - http://my_standalone_alertmanager:9093
```

I'm thinking maybe the name of the property items or the order they are in or something like that is wrong, but it's hard to say as I don't have a good config to reference/compare.

The end goal will be to send alerts to multiple different alert managers at the same time.  If you know of any other way to achieve this, please let me know.

**Comment by psycofdj** [comment]
In addition to the mentioned spec, the configuration also uses [bosh links](https://bosh.io/docs/links). 

https://github.com/bosh-prometheus/prometheus-boshrelease/blob/66868a788deb46f6ebe7cbe9482c55a09e120980/jobs/prometheus2/spec#L21-L23

Do you deploy the the default alertmanager included in prometheus deployment ? If so, you can either:

- delete the alert manager from the deployment: 
```yaml
- type: remove
  path: /instance_groups/name=alertmanager
```

- explicitly remove the generated [link](https://bosh.io/docs/links/#explicit)
```yaml
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/consumes?/alertmanager
  value: nil
```

Below the piece of template that generates the actual configuration:

https://github.com/bosh-prometheus/prometheus-boshrelease/blob/66868a788deb46f6ebe7cbe9482c55a09e120980/jobs/prometheus2/templates/config/prometheus.yml#L41-L52

**Comment by pcfadminx** [comment]
@psycofdj 
I am able to deploy it without the included alert manager.  But the issue is I'm not able to get prometheus to point to the external alertmanager.  

I can do it manually by SSHing into prometheus and changing settings manually, but need a way to do this through the manifest.

**Comment by psycofdj** [comment]
The linked spec is new in latest [v26.7.0](https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v26.7.0) and I assume you're running a previous version of this bosh release.

In prior versions, you can use [manual bosh link configuration](https://bosh.io/docs/links-manual/) as follow:

```yaml
# this is manual bosh link configuration 
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/consumes?
  value:
    alertmanager:
      instances:
      - address: first.alertmanager.domain.org
      - address: second.alertmanager.domain.org
      properties:
        alertmanager:
          web:
            port: 9093
```

This approach is also compatible with the latest version [v26.7.0](https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v26.7.0).

**Comment by pcfadminx** [comment]
@psycofdj 

I am indeed on an older version.  Your link configuration worked perfectly for one of my alertmanager environments, but not the second.

My second alertmanager is an API that listens on plain HTTP and works as a bridge, forwarding payloads to other alertmanager instances that do run on port 9093.  

The flow is like this: prometheus 2 > **http://second.alertmanager.domain.org/api/v1/alerts** > other alertmanagers.

In the below snippet, I tried to change the port to 80 which sets the target as **http://second.alertmanager.domain.org/api/v1/alerts:80**, but it isn't reachable.  I also tried setting the port to null in the config below, but the deployment fails saying it expects a value for alertmanager.web.port

If I ssh and manually edit the config of the instance to take port 80 off, it does work.  So I just need to figure out how to set it up without ports.

```
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/consumes?
  value:
    alertmanager:
      instances:
      - address: http://second.alertmanager.domain.org/api/v1/alerts # Does not use port 9093
      properties:
        alertmanager:
          web:
            port: null # set to null so it doesn't point to any ports
```

**Comment by pcfadminx** [comment]
Update: I was able to get it to work on 26.7.0

But I can't get addresses with paths to work.  How would I pass an address that includes paths?  e.g. **second.alertmanager.domain.org/some/path**

`error msg="Error loading config (--config.file=/var/vcap/jobs/prometheus2/config/prometheus.yml)" err="parsing YAML file /var/vcap/jobs/prometheus2/config/prometheus.yml: \”second.alertmanager.domain.org/some/path\" is not a valid hostname"`

**Comment by psycofdj** [comment]
```yaml
  jobs:
  - name: prometheus2
    properties:
      prometheus:
        alertmanagers:
        - static_configs:
          - path_prefix: /to/my/path
            targets:
            - first.alertmanager.domain.org:<port>
            - second.alertmanager.domain.org:<port>
```

**Comment by pcfadminx** [comment]
I modified my ops file to this and it seems to be working.  Thanks!

```
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties?/prometheus/alertmanagers/-
  value:
    path_prefix: /to/my/path
    static_configs:
      - targets: ["second.alertmanager.domain.org:9093"]
```
